# Generated by Django 5.2.5 on 2025-09-08 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeE', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='first_update',
        ),
    ]
