# Generated by Django 5.2.5 on 2025-09-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeE', '0002_remove_product_first_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
