# Generated by Django 5.2.5 on 2025-09-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeE', '0005_alter_collection_options_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
